apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    uid: loki
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    httpMethod: GET
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
