{
 "title": "stor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node total size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (node_total_size) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node chunks",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (node_total_chunks) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "cd0dce76", "operator": "=", "scope": "span", "tag": "" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "stor.node" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "http.Health" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "front logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"stor.front\"} |= ``"
    }
   ]
  },
  {
   "title": "nodes logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"stor.node\"} |= ``"
    }
   ]
  }
 ]
}